<a href="https://colab.research.google.com/github/StephenMuuo/Karamoja-Data-Visualisation-project/blob/main/Karamoja%20data%20cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Final Project Submission

Please fill out:
* Student name: Stephen Muuo Munyiala
* Student pace: part time
* Scheduled project review date/time: 01/09/2024
* Instructor name:Mr. Samwel Jane and Ms. Veronica Isiaho.
* Blog post URL:

  KARAMOJA DATASET CLEANING.

Importing libraries.

In [1]:
#Import Libraries.
import pandas as pd

Uploading the data.

In [2]:
#Loading Karamoja District data.
District_data=pd.read_csv('/content/Uganda_Karamoja_District_Crop_Yield_Population.csv')

#Loading Karamoja Subcounty data.
Subcounty_data=pd.read_csv('/content/Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv')

Preview of the Data.

In [3]:
#Preview of the First five rows to confirm data is present.
District_data.head()

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,92,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567
1,96,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558
2,20,KAABONG,627057,7373606003,279,945,28121.672530,20544.194960,7394.416334,5731830,6987723
3,85,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575
4,5,MOROTO,127811,3570160948,128,355,5954.814048,4741.748776,1190.050606,606944,422468

In [4]:
#Preview of the First five rows to confirm data is present.
Subcounty_data.head()

,OBJECTID,SUBCOUNTY_NAME,DISTRICT_NAME,POP,Area,Karamoja,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,263,KACHERI,KOTIDO,17244,1067176155,Y,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,600723.892900
1,264,KOTIDO,KOTIDO,52771,597575188,Y,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,959201.382500
2,265,KOTIDO TOWN COUNCIL,KOTIDO,27389,23972401,Y,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9991.488268
3,266,NAKAPERIMORU,KOTIDO,38775,419111591,Y,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,38971.659080
4,267,PANYANGARA,KOTIDO,65704,880955930,Y,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,221609.511400

Checking the range of the data.

In [5]:
#Checking to see the values in the District dataset.
District_data.shape
District_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OBJECTID      7 non-null      int64
 1   NAME          7 non-null      object
 2   POP           7 non-null      int64
 3   Area          7 non-null      int64
 4   S_Yield_Ha    7 non-null      int64
 5   M_Yield_Ha    7 non-null      int64
 6   Crop_Area_Ha  7 non-null      float64
 7   S_Area_Ha     7 non-null      float64
 8   M_Area_Ha     7 non-null      float64
 9   S_Prod_Tot    7 non-null      int64
 10  M_Prod_Tot    7 non-null      int64
dtypes: float64(3), int64(7), object(1)
memory usage: 744.0+ bytes

In [6]:
#Checking to see the values in the Subcounty dataset.
Subcounty_data.shape
Subcounty_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBJECTID        52 non-null     int64
 1   SUBCOUNTY_NAME  52 non-null     object
 2   DISTRICT_NAME   52 non-null     object
 3   POP             52 non-null     int64
 4   Area            52 non-null     int64
 5   Karamoja        52 non-null     object
 6   S_Yield_Ha      52 non-null     float64
 7   M_Yield_Ha      52 non-null     float64
 8   Crop_Area_Ha    52 non-null     float64
 9   S_Area_Ha       52 non-null     float64
 10  M_Area_Ha       52 non-null     float64
 11  S_Prod_Tot      52 non-null     float64
 12  M_Prod_Tot      52 non-null     float64
dtypes: float64(7), int64(3), object(3)
memory usage: 5.4+ KB

Inspecting the data for any errors.

In [7]:
#Checking for Null values.
District_data.isnull().sum()

OBJECTID        0
NAME            0
POP             0
Area            0
S_Yield_Ha      0
M_Yield_Ha      0
Crop_Area_Ha    0
S_Area_Ha       0
M_Area_Ha       0
S_Prod_Tot      0
M_Prod_Tot      0
dtype: int64

In [8]:
#Checking for null values in Sub county data.
Subcounty_data.isnull().sum()

OBJECTID          0
SUBCOUNTY_NAME    0
DISTRICT_NAME     0
POP               0
Area              0
Karamoja          0
S_Yield_Ha        0
M_Yield_Ha        0
Crop_Area_Ha      0
S_Area_Ha         0
M_Area_Ha         0
S_Prod_Tot        0
M_Prod_Tot        0
dtype: int64

In [9]:
#Checking for duplicates in District data.
District_data.duplicated().sum()

0

In [10]:
#Checking for duplicates in Subcounty data.
Subcounty_data.duplicated().sum()

0

Merging the data.

In [15]:
#Merging the Subcounty data with the District data using 'Name' and 'District Name' columns
Karamoja_data=pd.merge(Subcounty_data,District_data,left_on='SUBCOUNTY_NAME',right_on='NAME',suffixes=('_subcounty', '_district'))
Karamoja_data.head()

,OBJECTID_subcounty,SUBCOUNTY_NAME,DISTRICT_NAME,POP_subcounty,Area_subcounty,Karamoja,S_Yield_Ha_subcounty,M_Yield_Ha_subcounty,Crop_Area_Ha_subcounty,S_Area_Ha_subcounty,...,NAME,POP_district,Area_district,S_Yield_Ha_district,M_Yield_Ha_district,Crop_Area_Ha_district,S_Area_Ha_district,M_Area_Ha_district,S_Prod_Tot_district,M_Prod_Tot_district
0,264,KOTIDO,KOTIDO,52771,597575188,Y,367.890523,1162.996687,13587.990760,12455.592640,...,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575
1,765,ABIM,ABIM,14377,188613057,Y,501.263249,1183.089648,999.371589,593.531315,...,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567
2,812,AMUDAT,AMUDAT,30181,596393139,Y,239.047878,1379.045945,1651.998420,676.783266,...,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558

Saving the data.

In [16]:
#Saving the merged data.
Karamoja_data.to_csv('Karamoja_data.csv')